{% set version = "41" %}

package:
  name: ngspice-suite
  version: {{ version }}

source:
  url: https://downloads.sourceforge.net/project/ngspice/ng-spice-rework/old-releases/{{ version }}/ngspice-{{ version }}.tar.gz
  sha256: 1ce219395d2f50c33eb223a1403f8318b168f1e6d1015a7db9dbf439408de8c4

  patches:
    - patches/libtoolize-name.patch
    - patches/fix-xspice-ldflags.patch
    - patches/vngspice-install-location.patch  # [win]

build:
  number: 1

outputs:
  - name: ngspice-lib
    script: build_common.sh   # [unix]
    script: build_lib.bat     # [win]

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - llvm-openmp  # [osx]
        - libgomp      # [linux]
        - autoconf     # [unix]
        - automake     # [unix]
        - make         # [unix]
        - libtool      # [unix]
        - texinfo      # [unix]
        - bison        # [unix]
        - flex         # [unix]

      host:
        - llvm-openmp  # [osx]
        - libgomp      # [linux]
        - ncurses      # [unix]
        - readline     # [unix]

        # technically this ought to be in the 'build' requirements,
        # but it's easier to locate if we put it here, via LIBRARY_BIN
        - winflexbison   # [win]

    test:
      commands:
        - test -f $PREFIX/lib/libngspice{{ SHLIB_EXT }}            # [unix]
        - if not exist %LIBRARY_PREFIX%\\bin\\ngspice.dll exit 1   # [win]

  - name: ngspice-exe
    script: build_common.sh   # [unix]
    script: build_exe.bat     # [win]

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - llvm-openmp  # [osx]
        - libgomp      # [linux]
        - autoconf     # [unix]
        - automake     # [unix]
        - make         # [unix]
        - libtool      # [unix]
        - texinfo      # [unix]
        - bison        # [unix]
        - flex         # [unix]

      host:
        - {{ pin_subpackage('ngspice-lib', exact=True) }}
        - llvm-openmp  # [osx]
        - libgomp      # [linux]
        - ncurses      # [unix]
        - readline     # [unix]
        - xorg-libx11  # [unix]
        - xorg-libxaw  # [unix]
        - xorg-libxt   # [unix]

        # technically this ought to be in the 'build' requirements,
        # but it's easier to locate if we put it here, via LIBRARY_BIN
        - winflexbison   # [win]

      run:
        - {{ pin_subpackage('ngspice-lib', exact=True) }}

    test:
      files: test.cir
      commands:
        - ngspice --version
        - ngspice -b -r raw.out test.cir
        # Console specific commandline program for windows only
        - ngspice_con --version                          # [win]

  - name: ngspice
    requirements:
      run:
        - {{ pin_subpackage('ngspice-lib', exact=True) }}
        - {{ pin_subpackage('ngspice-exe', exact=True) }}

    test:
      commands:
        - ngspice --version
        # Console specific commandline program for windows only
        - ngspice_con.exe --version                               # [win]

about:
  home: http://ngspice.sourceforge.net
  doc_url: http://ngspice.sourceforge.net/docs.html
  dev_url: http://ngspice.sourceforge.net/devel.html

  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING

  summary: The open source spice simulator for electric and electronic circuits
  description: |
    ngspice is the open source spice simulator for electric and electronic circuits.

    Such a circuit may comprise of JFETs, bipolar and MOS transistors, passive elements
    like R, L, or C, diodes, transmission lines and other devices, all interconnected
    in a netlist. Digital circuits are simulated as well, event driven and fast, from
    single gates to complex circuits. And you may enter the combination of both analog
    and digital as a mixed-signal circuit.

    ngspice offers a wealth of device models for active, passive, analog, and digital
    elements. Model parameters are provided by the semiconductor manufacturers.
    The user add her circuits as a netlist, and the output is one or more graphs of
    currents, voltages and other electrical quantities or is saved in a data file.

    Note:
      This build was configured with `--enable-xspice --enable-cider --enable=openmp`
      See the [build script](https://git.io/JfVZX) for more specifics.

extra:
  recipe-maintainers:
    - stuarteberg
